command: ["uvicorn", "src.main:app"]

env:
  - name: 'DATABRICKS_DATABASE_INSTANCE'
    value: 'gdoyle-oltp-demo'
  - name: 'DATABRICKS_DATABASE_NAME'
    value: 'gdoyle'
  - name: 'DATABRICKS_DATABASE_PORT'
    value: '5432'

  - name: 'DB_POOL_SIZE'
    value: '5'
  - name: 'DB_MAX_OVERFLOW'
    value: '10'
  - name: 'DB_COMMAND_TIMEOUT'
    value: '30'
  - name: 'DB_POOL_TIMEOUT'
    value: '10'